# Generated by Django 4.1.11 on 2023-09-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('fecha_ingreso', models.CharField(max_length=20)),
                ('hora_ingreso', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('tiempo', models.CharField(max_length=20)),
                ('ruta', models.CharField(max_length=200)),
                ('dispositivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Estadistica',
        ),
    ]
